name: NodeCI

on:
  - push
  - pull_request

jobs:
  node-ci:
    name: NodeCI

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install
        run: make install
      - name: Linters
        run: make lint
      - name: Tests
        run: make test
      - name: Build
        run: make build
      - name: Publish test coverage
        uses: paambaati/codeclimate-action@v2.7.4
        env:
          CC_TEST_REPORTER_ID: ${{ secrets.CODE_CLIMATE_ID }}
        with:
          coverageCommand: make test-coverage
          debug: true